version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-cloud-resume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hly816qtdaha"
s3_prefix = "my-cloud-resume"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
